version: 2

formats: all
      
sphinx:
  fail_on_warning: true
    
python:
  # Install our python package before building the docs
  install:
    - requirements: requirements/pip.txt
    - requirements: requirements/docs.txt

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
