version: 2

formats: all
      
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
    
python:
  # Install our python package before building the docs
  install:
    - requirements: docs//source/requirements.txt
    - method: pip
      path: .

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
